### ISSUE TITLE
link的时候报错

### ISSUE THREAD

**Issue by WhynoChinese** [stoneWeb/elm-react-native#7]
module.js:328
    throw err;
    ^

Error: Cannot find module 'invariant'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mac/Desktop/elm-react-native/node_modules/react-native/packager/react-packager/src/lib/GlobalTransformCache.js:16:19)
    at Module._compile (module.js:398:26)
    at loader (/Users/mac/Desktop/elm-react-native/node_modules/react-native/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mac/Desktop/elm-react-native/node_modules/react-native/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by stoneWeb** [comment]
https://github.com/facebook/react-native/issues/11327
run `npm i --save-dev invariant`
